import pandas as pd
from fpdf import FPDF
import os

data_file_path = "data/sales_data.csv"

if not os.path.exists(data_file_path):
    print("Data file not found!")
    exit()

df = pd.read_csv(data_file_path)

summary = df.groupby("Month")["Sales"].sum().reset_index()

if not os.path.exists("reports"):
    os.makedirs("reports")

class PDFReport(FPDF):
    def header(self):
        self.set_fill_color(33, 150, 243)  
        self.rect(0, 0, self.w, 40, 'F')
        
        self.set_font("Arial", "B", 18)
        self.set_text_color(255, 255, 255)  
        self.cell(0, 30, "Monthly Sales Report", ln=True, align="C")
        
        self.set_font("Arial", "I", 12)
        self.cell(0, 10, "Generated by Report Generator Bot", ln=True, align="C")
        self.cell(0, 10, "", ln=True)  

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(150, 150, 150) 
        self.cell(0, 10, f"Page {self.page_no()}", 0, 0, "C")

    def add_table(self, data):
        table_width = 160
        start_x = (self.w - table_width) / 2
        self.set_x(start_x)

        self.set_fill_color(63, 81, 181)  
        self.set_text_color(255, 255, 255)  
        self.set_font("Arial", "B", 12)
        self.cell(80, 10, "Month", 1, 0, "C", fill=True)
        self.cell(80, 10, "Total Sales", 1, 1, "C", fill=True)

        self.set_text_color(0, 0, 0)  
        self.set_font("Arial", "", 12)
        fill = False
        for index, row in data.iterrows():
            self.set_x(start_x)  
            self.cell(80, 10, row["Month"], 1, 0, "C", fill=fill)
            self.cell(80, 10, f"${row['Sales']:.2f}", 1, 1, "C", fill=fill)

        self.cell(0, 10, "", ln=True)  

    def add_summary(self, data):
        total_sales = data["Sales"].sum()
        self.set_text_color(33, 150, 243)  
        self.set_font("Arial", "B", 14)
        self.cell(0, 10, f"Total Sales for All Months: ${total_sales:.2f}", ln=True, align="C")

pdf = PDFReport()
pdf.add_page()

pdf.add_table(summary)
pdf.add_summary(summary)

pdf_output_path = "reports/sales_report.pdf"
pdf.output(pdf_output_path)
print(f"Report has been saved to {pdf_output_path}")
